spring:
  application:
    name: notification-server
  config:
    import: optional:configserver:http://config-server:8888
  servlet:
    multipart:
      max-file-size: 50MB

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # expiration token
      expiration: 86400000 # a day
      # refresh token
      refresh-token:
        expiration: 604800000 # 7 days

server:
  servlet:
    context-path: /api/v1/