spring:
  application:
    name: feedback-server
  config:
    import: optional:configserver:http://localhost:8888
  servlet:
    multipart:
      max-file-size: 50MB

server:
  servlet:
    context-path: /api/v1/
