spring:
  application:
    name: user-server
  config:
    import: optional:configserver:http://config-server:8888

  mail:
    host: smtp.gmail.com
    port: 465
    username: gmail_account@gmail.com
    password:  gmail_password
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: "*"
          starttls:
            enable: true
    protocol: smtp

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      # expiration token
      expiration: 86400000 # a day
      # refresh token
      refresh-token:
        expiration: 604800000 # 7 days
  mailing:
    frontend:
      activation-url: http://localhost:8080/activate-account
  file:
      uploads:
        photos-output-path: ./uploads
# port
server:
  port: 8088










