eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8085



spring:
  application:
    name: book-server
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://mysql-bsn:3306/books?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans

application:
  config:
    auth-url: http://gateway:8222/api/v1/auth
    feedback-service-url: http://gateway:8222/api/v1/feedbacks
    transaction-history-service-url:  http://gateway:8222/api/v1/histories


