eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-server
          uri: http://user-server:8088
          predicates:
            - Path=/api/v1/auth/**
        - id: book-server
          uri: http://book-server:8085
          predicates:
            - Path=/api/v1/books/**
        - id: transactionHistory-server
          uri: http://transaction-server:8086
          predicates:
            - Path=/api/v1/transactions/**
        - id: feedback-server
          uri: http://feedback-server:8087
          predicates:
            - Path=/api/v1/feedbacks/**
        - id: notification-server
          uri: http://notification-server:8070
          predicates:
            - Path=/api/v1/notifications/**



springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Server
        url: /v3/api-docs
      - name: User Server
        url: http://localhost:8088/api/v1/v3/api-docs
      - name: Book Server
        url: http://localhost:8085/api/v1/v3/api-docs
      - name: Transaction History Service
        url: http://localhost:8086/api/v1/v3/api-docs
      - name: Feedback Server
        url: http://localhost:8087/api/v1/v3/api-docs


management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
