eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/v1/auth/**
        - id: book-server
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/books/**
        - id: transactionHistory-server
          uri: http://localhost:8086
          predicates:
            - Path=/api/v1/transactions/**
        - id: feedback-server
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/feedbacks/**



springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: API Gateway Service
        url: /v3/api-docs
      - name: Auth Service
        url: http://localhost:8088/api/v1/v3/api-docs
      - name: Book Service
        url: http://localhost:8085/api/v1/v3/api-docs
      - name: Transaction History Service
        url: http://localhost:8086/api/v1/v3/api-docs
      - name: Feedback Service
        url: http://localhost:8087/api/v1/v3/api-docs


management:
  tracing:
    sampling:
      probability: 1.0