eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8070

spring:
  application:
    name: notification-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint: http://tempo:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
