eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

server:
  port: 8086

spring:
  application:
    name: transactionHistory-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql-bsn:3306/histories?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"


application:
  config:
    auth-url: http://gateway:8222/api/v1/auth
    feedback-server-url: http://gateway:8222/api/v1/feedbacks
    book-server-url:  http://gateway:8222/api/v1/books
    notification-server-url: http://gateway:8222/api/v1/notifications