eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8086

spring:
  application:
    name: transactionHistory-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/histories?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  config:
    auth-url: http://localhost:8222/api/v1/auth
    feedback-server-url: http://localhost:8222/api/v1/feedbacks
    book-server-url:  http://localhost:8222/api/v1/books